### PR TITLE
remove sponsor members

### PR DESCRIPTION
**Pull request by MarkMangoba**
remove sponsor membership, this was eliminated 2 years ago.

### CODE REVIEW

**Comment by gvanrossum** [comment]
@VanL Is this correct? If so why was this out of date for two years?
@MarkMangoba Is there a document to back up this claim?

**Comment by MarkMangoba** [comment]
@gvanrossum our current membership levels are (https://www.python.org/psf/members/#membership-categories)
- Fellows are elected on merit
- Emeritus Fellows are no longer active in the PSF
- Contributing / managing members support the PSF's mission by actively engaging in bringing Python forward
- Supporting members support the PSF by paying a yearly membership fee
- Basic members show their support for Python by signing up to the PSF
  
The sponsorship membership level was revamped about two years ago.  @ejodlowska will have more context to the resolution.

**Comment by gvanrossum** [comment]
But the bylaws can only be changed if the procedure stated in the bylaws is followed. Was it? (If not, the board will need to take steps to follow the proper procedure to update them before you can land this.)

**Comment by MarkMangoba** [comment]
@gvanrossum RESOLVED, that the Python Software Foundation amend the PSF bylaws to remove the Sponsor Membership category. All changes made by the Bylaws WG are listed here: https://bitbucket.org/malemburg/psf-bylaws/diff/bylaws.md?diff1=ba846896778b&diff2=fa6ce90a3f1376b2708bf76d87c70813f96e010a&at=default

The vote was resolved on Tue, May 24, 2016.

**Comment by MarkMangoba** [comment]
@gvanrossum I believe @VanL will need to review this a bit more.  The by-laws we're updated in June and something must have happened in between the transition from V1 to V2.

**Comment by VanL** [comment]
There was a "scrivener's error" when moving from bitbucket to git. Some of the changes were redone in git to show history and diffs for voting purposes.

**Comment by gvanrossum** [comment]
Thanks for clearing this up, Van!

**Pull request merged**
