### PR TITLE
cleaning up more transfer issues

### PR DESCRIPTION
**Pull request by MarkMangoba**
cleaning up issues transfer from Bitbucket -> GitHub

### CODE REVIEW

**Comment by VanL** [comment]
Hi Mark,

Can you rebase the commit on the version that is in the repository here? It is hard to verify the changes in the format you have provided. Specifically:

- Some of the use of markdown has been changed ("*" to "_", "===" to "#", etc.), creating noise where the changes are non-substantive

- Line breaks have been removed or added

- There are some smart quotes instead of straight quotes

The end result is that to diff it looks like a complete delete of all contents of the file, followed by insertion of totally new content. 

Can you isolate the changes in the PR to particular paragraphs and update the commit?

**Comment by MarkMangoba** [comment]
Hi @VanL - I corrected the formatting issues, my apologies, it didn't copy over from the old Bitbucket repo correctly.

**Comment by VanL** [comment]
Hi Mark,

This is much better, but it deletes a number of other changes that have been approved:

- Yearly certification has been dropped, now it is just certification as required by the board;
- We have the 3-year rotating terms now;
- The version here looks like it already has the organizational members dropped in section 4, other than the textual fix from six classes to five

Most of the fixes from Section 4 on down should not be merged and they should be backed out of the pull request. The things that look like they should be kept are:
- Change around line 186
- Change in 4.1 (six to five classes)
- Changes around 248-250 (plus or minus)
- Change in 5.2

Thanks for your work on this, Mark!

**Comment by MarkMangoba** [comment]
@VanL it looks like the issue here is: 

**Section 4.6. Managing Members.** To be eligible for membership as 
**Section 4.6** Removed.

Lines 290-291, should we still list **Section 4.6** Removed and move everything else below section 4.6 up?

**Review by VanL — APPROVED** [review]
Made a few changes, ready for commit.

**Pull request merged**
